src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 */
class Users
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_insc;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tasks", mappedBy="userId")
     * @ORM\JoinColumn(nullable=false)
     *
     */
    private $listTasks;
    private $UsersRepository;

    public function __construct()
    {
        $this->listTasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateInsc(): ?\DateTimeInterface
    {
        return $this->date_insc;
    }

    public function setDateInsc(\DateTimeInterface $date_insc): self
    {
        $this->date_insc = $date_insc;

        return $this;
    }

    public function getTaskId(): ?Tasks
    {
        return $this->taskId;
    }

    public function setTaskId(?Tasks $taskId): self
    {
        $this->taskId = $taskId;

        return $this;
    }

    public function getUserId(): ?Users
    {
        return $this->userId;
    }

    public function setUserId(?Users $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getUsersRepository(): ?string
    {
        return $this->UsersRepository;
    }

    public function setUsersRepository(string $UsersRepository): self
    {
        $this->UsersRepository = $UsersRepository;

        return $this;
    }

}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => false,
                'attr' => ["placeholder" => "Nom"]
            ])
            ->add('prenom', TextType::class, [
                'label' => false,
                'attr' => ["placeholder" => "Prenom"]
            ])
            ->add('email', TextType::class, [
                'label' => false,
                'attr' => ["placeholder" => "Email"]
            ])
            ->add('date_insc', DateTimeType::class, array(
                "data" => new \DateTime('now')
            ))
            ->add('submit', SubmitType::class, [
                'attr' => ["class" => 'btn btn-primary']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Entity\Tasks;
use App\Form\UpdateUserType;
use App\Form\UsersType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class UsersController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(EntityManagerInterface $entityManager, Request $request)
    {

        $user = new Users();

        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        $taskRepository = $this->getDoctrine()
            ->getRepository(Tasks::class);


        if ($form->isSubmitted() && $form->isValid()){

            $task = $taskRepository->find($request->request->get('taskId'));

            $user = $form->getData();
            $user->setTaskId($task);

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }
        
        $usersRepository = $this->getDoctrine()
        ->getRepository(Users::class)->findAll();
        $tasks = $taskRepository->findAll();

        return $this->render('users/index.html.twig', [
            'users' => $usersRepository,
            'userForm' => $form->createView(),
            'tasks' => $tasks
        ]);
    }

    /**
     * @Route("/users/update/{id}", name="updateUser")
     */
    public function update($id, Request $request, EntityManagerInterface $entityManager)
    {
        $user = $this->getDoctrine()
            ->getRepository(Users::class)->find($id);


        $form = $this->createForm(UpdateUserType::class, $user);
        $form->handleRequest($request);

        $userRepository = $this->getDoctrine()
            ->getRepository(Users::class);


        if ($form->isSubmitted() && $form->isValid()){

            $user = $userRepository->find($request->request->get('userId'));

            $task = $form->getData();
            $task->setTaskId($user);

            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        $tasksRepository = $this->getDoctrine()
            ->getRepository(Tasks::class)->findAll();
        $users = $userRepository->findAll();

        return $this->render('users/update.html.twig', [
            'tasks' => $tasksRepository,
            'formUpdateUser' => $form->createView(),
            'users' => $users
        ]);
    }


}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UsersController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <h1>Les Utilisateurs</h1>
        </div>
        <div class="container">
            {% for user in users %}

                    <div class="card">
                        <div class="card-body">
                            <ul>{{ user.nom }} {{ user.prenom }}<br> {{ user.email }}
                                <br>{{ user.dateInsc | date('d/m/Y H:i:s') }}</ul>
                            <a href="{{path('updateUser', {id: user.id})}}"><button class="btn btn-warning">Modifier</button></a>
                        </div>
                    </div>
            {% endfor %}
        </div>

        <div class="container mt-5">
            {{ form_start(userForm) }}
            <select name="taskId" id="">
                {% for task in tasks %}
                    <option value="{{ task.id }}">Tâche à assigner : {{ task.name }}</option>
                {% endfor %}
            </select>
            <br>
            <br>
            Quel utilisateur va réaliser cette tâche ?
            {{ form_end(userForm) }}

        </div>
    </div>

{% endblock %}

templates/users/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mt-5">
        <h1>Modifier l'utilisateur </h1>

        <div class="container mt-5">
            {{ form_start(formUpdateUser) }}
            <select name="userId" id="" style="display: none">
                {% for user in users %}
                    <option></option>
                {% endfor %}
            </select>
             {{ form_end(formUpdateUser) }}
        </div>
    </div>

{% endblock body %}